--create user sqluser identified by 12345;
--alter user sqluser quota unlimited on users;
--Grant connect, ReSouRce to sqluser;




create table Users(
    id_v integer generated by default as identity primary key,
    fio VARCHAR2(200) not null
);
create table users_history(
    id_h integer generated by default as identity primary key,
    old_fio varchar(200) not NULL,
    new_fio varchar(200) not null,
    date_v varchar(200) not null,
    id_v number references Users(id_v)
);

create or replace trigger trg_user_hist
Before update on users
for each row
Begin 
    if :new.fio!=:old.fio then
        insert into users_history(id_v,old_fio,new_fio,date_v)
        values(:old.id_v, :old.fio, :new.fio, sysdate);
    END IF;
END;


INSERT  into Users(FIO) VALUES('Иванов Иван Иванович');
COMMIT; 

update users set fio = 'Петров Петр Петрович'
where id_v = 1


------

------